/*
 * generated by Xtext 2.20.0
 */
package mil.navy.nrl.ncarai.jasm.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ProgramAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("mil/navy/nrl/ncarai/jasm/parser/antlr/internal/InternalProgram.tokens");
	}
}
