/*
 * generated by Xtext 2.20.0
 */
package mil.navy.nrl.ncarai.jasm.parser.antlr;

import com.google.inject.Inject;
import mil.navy.nrl.ncarai.jasm.parser.antlr.internal.InternalProgramParser;
import mil.navy.nrl.ncarai.jasm.services.ProgramGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ProgramParser extends AbstractAntlrParser {

	@Inject
	private ProgramGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalProgramParser createParser(XtextTokenStream stream) {
		return new InternalProgramParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public ProgramGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ProgramGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
