/*
 * generated by Xtext 2.20.0
 */
package mil.navy.nrl.ncarai.jasm.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.jactr.io2.jactr.validation.ModelFragmentValidator;

public abstract class AbstractProgramValidator extends ModelFragmentValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>(super.getEPackages());
		result.add(mil.navy.nrl.ncarai.jasm.program.ProgramPackage.eINSTANCE);
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.jactr.org/io2/jactr/ModelFragment"));
		return result;
	}
}
