/**
 * generated by Xtext 2.20.0
 */
package mil.navy.nrl.ncarai.jasm.program.impl;

import java.util.Collection;

import mil.navy.nrl.ncarai.jasm.program.BufferDef;
import mil.navy.nrl.ncarai.jasm.program.ProgramPackage;
import mil.navy.nrl.ncarai.jasm.program.RequestDef;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Buffer Def</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.impl.BufferDefImpl#getName <em>Name</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.impl.BufferDefImpl#isReadable <em>Readable</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.impl.BufferDefImpl#isWritable <em>Writable</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.impl.BufferDefImpl#isError <em>Error</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.impl.BufferDefImpl#getRequests <em>Requests</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BufferDefImpl extends MinimalEObjectImpl.Container implements BufferDef
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #isReadable() <em>Readable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isReadable()
   * @generated
   * @ordered
   */
  protected static final boolean READABLE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isReadable() <em>Readable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isReadable()
   * @generated
   * @ordered
   */
  protected boolean readable = READABLE_EDEFAULT;

  /**
   * The default value of the '{@link #isWritable() <em>Writable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isWritable()
   * @generated
   * @ordered
   */
  protected static final boolean WRITABLE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isWritable() <em>Writable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isWritable()
   * @generated
   * @ordered
   */
  protected boolean writable = WRITABLE_EDEFAULT;

  /**
   * The default value of the '{@link #isError() <em>Error</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isError()
   * @generated
   * @ordered
   */
  protected static final boolean ERROR_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isError() <em>Error</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isError()
   * @generated
   * @ordered
   */
  protected boolean error = ERROR_EDEFAULT;

  /**
   * The cached value of the '{@link #getRequests() <em>Requests</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRequests()
   * @generated
   * @ordered
   */
  protected EList<RequestDef> requests;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BufferDefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ProgramPackage.Literals.BUFFER_DEF;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProgramPackage.BUFFER_DEF__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isReadable()
  {
    return readable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReadable(boolean newReadable)
  {
    boolean oldReadable = readable;
    readable = newReadable;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProgramPackage.BUFFER_DEF__READABLE, oldReadable, readable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isWritable()
  {
    return writable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWritable(boolean newWritable)
  {
    boolean oldWritable = writable;
    writable = newWritable;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProgramPackage.BUFFER_DEF__WRITABLE, oldWritable, writable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isError()
  {
    return error;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setError(boolean newError)
  {
    boolean oldError = error;
    error = newError;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProgramPackage.BUFFER_DEF__ERROR, oldError, error));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<RequestDef> getRequests()
  {
    if (requests == null)
    {
      requests = new EObjectContainmentEList<RequestDef>(RequestDef.class, this, ProgramPackage.BUFFER_DEF__REQUESTS);
    }
    return requests;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ProgramPackage.BUFFER_DEF__REQUESTS:
        return ((InternalEList<?>)getRequests()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ProgramPackage.BUFFER_DEF__NAME:
        return getName();
      case ProgramPackage.BUFFER_DEF__READABLE:
        return isReadable();
      case ProgramPackage.BUFFER_DEF__WRITABLE:
        return isWritable();
      case ProgramPackage.BUFFER_DEF__ERROR:
        return isError();
      case ProgramPackage.BUFFER_DEF__REQUESTS:
        return getRequests();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ProgramPackage.BUFFER_DEF__NAME:
        setName((String)newValue);
        return;
      case ProgramPackage.BUFFER_DEF__READABLE:
        setReadable((Boolean)newValue);
        return;
      case ProgramPackage.BUFFER_DEF__WRITABLE:
        setWritable((Boolean)newValue);
        return;
      case ProgramPackage.BUFFER_DEF__ERROR:
        setError((Boolean)newValue);
        return;
      case ProgramPackage.BUFFER_DEF__REQUESTS:
        getRequests().clear();
        getRequests().addAll((Collection<? extends RequestDef>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ProgramPackage.BUFFER_DEF__NAME:
        setName(NAME_EDEFAULT);
        return;
      case ProgramPackage.BUFFER_DEF__READABLE:
        setReadable(READABLE_EDEFAULT);
        return;
      case ProgramPackage.BUFFER_DEF__WRITABLE:
        setWritable(WRITABLE_EDEFAULT);
        return;
      case ProgramPackage.BUFFER_DEF__ERROR:
        setError(ERROR_EDEFAULT);
        return;
      case ProgramPackage.BUFFER_DEF__REQUESTS:
        getRequests().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ProgramPackage.BUFFER_DEF__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case ProgramPackage.BUFFER_DEF__READABLE:
        return readable != READABLE_EDEFAULT;
      case ProgramPackage.BUFFER_DEF__WRITABLE:
        return writable != WRITABLE_EDEFAULT;
      case ProgramPackage.BUFFER_DEF__ERROR:
        return error != ERROR_EDEFAULT;
      case ProgramPackage.BUFFER_DEF__REQUESTS:
        return requests != null && !requests.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", readable: ");
    result.append(readable);
    result.append(", writable: ");
    result.append(writable);
    result.append(", error: ");
    result.append(error);
    result.append(')');
    return result.toString();
  }

} //BufferDefImpl
