/**
 * generated by Xtext 2.20.0
 */
package mil.navy.nrl.ncarai.jasm.program.impl;

import mil.navy.nrl.ncarai.jasm.program.InsertionStatement;
import mil.navy.nrl.ncarai.jasm.program.ProgramPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Insertion Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.impl.InsertionStatementImpl#getEntryState <em>Entry State</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.impl.InsertionStatementImpl#getExitState <em>Exit State</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.impl.InsertionStatementImpl#isShouldGenerate <em>Should Generate</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InsertionStatementImpl extends InstructionImpl implements InsertionStatement
{
  /**
   * The default value of the '{@link #getEntryState() <em>Entry State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntryState()
   * @generated
   * @ordered
   */
  protected static final String ENTRY_STATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEntryState() <em>Entry State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntryState()
   * @generated
   * @ordered
   */
  protected String entryState = ENTRY_STATE_EDEFAULT;

  /**
   * The default value of the '{@link #getExitState() <em>Exit State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExitState()
   * @generated
   * @ordered
   */
  protected static final String EXIT_STATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getExitState() <em>Exit State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExitState()
   * @generated
   * @ordered
   */
  protected String exitState = EXIT_STATE_EDEFAULT;

  /**
   * The default value of the '{@link #isShouldGenerate() <em>Should Generate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isShouldGenerate()
   * @generated
   * @ordered
   */
  protected static final boolean SHOULD_GENERATE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isShouldGenerate() <em>Should Generate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isShouldGenerate()
   * @generated
   * @ordered
   */
  protected boolean shouldGenerate = SHOULD_GENERATE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InsertionStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ProgramPackage.Literals.INSERTION_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEntryState()
  {
    return entryState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEntryState(String newEntryState)
  {
    String oldEntryState = entryState;
    entryState = newEntryState;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProgramPackage.INSERTION_STATEMENT__ENTRY_STATE, oldEntryState, entryState));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getExitState()
  {
    return exitState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExitState(String newExitState)
  {
    String oldExitState = exitState;
    exitState = newExitState;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProgramPackage.INSERTION_STATEMENT__EXIT_STATE, oldExitState, exitState));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isShouldGenerate()
  {
    return shouldGenerate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setShouldGenerate(boolean newShouldGenerate)
  {
    boolean oldShouldGenerate = shouldGenerate;
    shouldGenerate = newShouldGenerate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProgramPackage.INSERTION_STATEMENT__SHOULD_GENERATE, oldShouldGenerate, shouldGenerate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ProgramPackage.INSERTION_STATEMENT__ENTRY_STATE:
        return getEntryState();
      case ProgramPackage.INSERTION_STATEMENT__EXIT_STATE:
        return getExitState();
      case ProgramPackage.INSERTION_STATEMENT__SHOULD_GENERATE:
        return isShouldGenerate();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ProgramPackage.INSERTION_STATEMENT__ENTRY_STATE:
        setEntryState((String)newValue);
        return;
      case ProgramPackage.INSERTION_STATEMENT__EXIT_STATE:
        setExitState((String)newValue);
        return;
      case ProgramPackage.INSERTION_STATEMENT__SHOULD_GENERATE:
        setShouldGenerate((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ProgramPackage.INSERTION_STATEMENT__ENTRY_STATE:
        setEntryState(ENTRY_STATE_EDEFAULT);
        return;
      case ProgramPackage.INSERTION_STATEMENT__EXIT_STATE:
        setExitState(EXIT_STATE_EDEFAULT);
        return;
      case ProgramPackage.INSERTION_STATEMENT__SHOULD_GENERATE:
        setShouldGenerate(SHOULD_GENERATE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ProgramPackage.INSERTION_STATEMENT__ENTRY_STATE:
        return ENTRY_STATE_EDEFAULT == null ? entryState != null : !ENTRY_STATE_EDEFAULT.equals(entryState);
      case ProgramPackage.INSERTION_STATEMENT__EXIT_STATE:
        return EXIT_STATE_EDEFAULT == null ? exitState != null : !EXIT_STATE_EDEFAULT.equals(exitState);
      case ProgramPackage.INSERTION_STATEMENT__SHOULD_GENERATE:
        return shouldGenerate != SHOULD_GENERATE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (entryState: ");
    result.append(entryState);
    result.append(", exitState: ");
    result.append(exitState);
    result.append(", shouldGenerate: ");
    result.append(shouldGenerate);
    result.append(')');
    return result.toString();
  }

} //InsertionStatementImpl
