/**
 * generated by Xtext 2.19.0
 */
package mil.navy.nrl.ncarai.jasm.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
@SuppressWarnings("all")
public class ProgramOutlineTreeProvider extends DefaultOutlineTreeProvider {
}
