/*
 * generated by Xtext 2.20.0
 */
package mil.navy.nrl.ncarai.jasm.ui;

import com.google.inject.Injector;
import mil.navy.nrl.ncarai.jasm.ui.internal.JasmActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ProgramExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(JasmActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		JasmActivator activator = JasmActivator.getInstance();
		return activator != null ? activator.getInjector(JasmActivator.MIL_NAVY_NRL_NCARAI_JASM_PROGRAM) : null;
	}

}
