/**
 * generated by Xtext 2.19.0
 */
package mil.navy.nrl.ncarai.jasm;

import mil.navy.nrl.ncarai.jasm.ProgramStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ProgramStandaloneSetup extends ProgramStandaloneSetupGenerated {
  public static void doSetup() {
    new ProgramStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
