/**
 * generated by Xtext 2.19.0
 */
package mil.navy.nrl.ncarai.jasm.ide;

import mil.navy.nrl.ncarai.jasm.ide.AbstractProgramIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ProgramIdeModule extends AbstractProgramIdeModule {
}
