/*
 * generated by Xtext 2.20.0
 */
package mil.navy.nrl.ncarai.jasm.scoping;

import org.jactr.io2.jactr.scoping.ModelFragmentScopeProvider;

public abstract class AbstractProgramScopeProvider extends ModelFragmentScopeProvider {
}
