/**
 * generated by Xtext 2.20.0
 */
package mil.navy.nrl.ncarai.jasm.program;

import org.eclipse.emf.ecore.EObject;

import org.jactr.io2.jactr.modelFragment.Buffer;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Buffer Pattern</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.BufferPattern#getBuffer <em>Buffer</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.BufferPattern#getPattern <em>Pattern</em>}</li>
 * </ul>
 *
 * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getBufferPattern()
 * @model
 * @generated
 */
public interface BufferPattern extends EObject
{
  /**
   * Returns the value of the '<em><b>Buffer</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Buffer</em>' reference.
   * @see #setBuffer(Buffer)
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getBufferPattern_Buffer()
   * @model
   * @generated
   */
  Buffer getBuffer();

  /**
   * Sets the value of the '{@link mil.navy.nrl.ncarai.jasm.program.BufferPattern#getBuffer <em>Buffer</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Buffer</em>' reference.
   * @see #getBuffer()
   * @generated
   */
  void setBuffer(Buffer value);

  /**
   * Returns the value of the '<em><b>Pattern</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pattern</em>' reference.
   * @see #setPattern(Pattern)
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getBufferPattern_Pattern()
   * @model
   * @generated
   */
  Pattern getPattern();

  /**
   * Sets the value of the '{@link mil.navy.nrl.ncarai.jasm.program.BufferPattern#getPattern <em>Pattern</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pattern</em>' reference.
   * @see #getPattern()
   * @generated
   */
  void setPattern(Pattern value);

} // BufferPattern
