/**
 * generated by Xtext 2.20.0
 */
package mil.navy.nrl.ncarai.jasm.program;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Buffer Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.BufferDef#getName <em>Name</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.BufferDef#isReadable <em>Readable</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.BufferDef#isWritable <em>Writable</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.BufferDef#isError <em>Error</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.BufferDef#getRequests <em>Requests</em>}</li>
 * </ul>
 *
 * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getBufferDef()
 * @model
 * @generated
 */
public interface BufferDef extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getBufferDef_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link mil.navy.nrl.ncarai.jasm.program.BufferDef#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Readable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Readable</em>' attribute.
   * @see #setReadable(boolean)
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getBufferDef_Readable()
   * @model
   * @generated
   */
  boolean isReadable();

  /**
   * Sets the value of the '{@link mil.navy.nrl.ncarai.jasm.program.BufferDef#isReadable <em>Readable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Readable</em>' attribute.
   * @see #isReadable()
   * @generated
   */
  void setReadable(boolean value);

  /**
   * Returns the value of the '<em><b>Writable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Writable</em>' attribute.
   * @see #setWritable(boolean)
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getBufferDef_Writable()
   * @model
   * @generated
   */
  boolean isWritable();

  /**
   * Sets the value of the '{@link mil.navy.nrl.ncarai.jasm.program.BufferDef#isWritable <em>Writable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Writable</em>' attribute.
   * @see #isWritable()
   * @generated
   */
  void setWritable(boolean value);

  /**
   * Returns the value of the '<em><b>Error</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Error</em>' attribute.
   * @see #setError(boolean)
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getBufferDef_Error()
   * @model
   * @generated
   */
  boolean isError();

  /**
   * Sets the value of the '{@link mil.navy.nrl.ncarai.jasm.program.BufferDef#isError <em>Error</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Error</em>' attribute.
   * @see #isError()
   * @generated
   */
  void setError(boolean value);

  /**
   * Returns the value of the '<em><b>Requests</b></em>' containment reference list.
   * The list contents are of type {@link mil.navy.nrl.ncarai.jasm.program.RequestDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Requests</em>' containment reference list.
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getBufferDef_Requests()
   * @model containment="true"
   * @generated
   */
  EList<RequestDef> getRequests();

} // BufferDef
