/**
 * generated by Xtext 2.20.0
 */
package mil.navy.nrl.ncarai.jasm.program;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Then Else Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.IfThenElseStatement#getBindings <em>Bindings</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.IfThenElseStatement#getThenBlock <em>Then Block</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.IfThenElseStatement#getElseBlock <em>Else Block</em>}</li>
 * </ul>
 *
 * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getIfThenElseStatement()
 * @model
 * @generated
 */
public interface IfThenElseStatement extends Instruction
{
  /**
   * Returns the value of the '<em><b>Bindings</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bindings</em>' containment reference.
   * @see #setBindings(Bindings)
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getIfThenElseStatement_Bindings()
   * @model containment="true"
   * @generated
   */
  Bindings getBindings();

  /**
   * Sets the value of the '{@link mil.navy.nrl.ncarai.jasm.program.IfThenElseStatement#getBindings <em>Bindings</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bindings</em>' containment reference.
   * @see #getBindings()
   * @generated
   */
  void setBindings(Bindings value);

  /**
   * Returns the value of the '<em><b>Then Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then Block</em>' containment reference.
   * @see #setThenBlock(Block)
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getIfThenElseStatement_ThenBlock()
   * @model containment="true"
   * @generated
   */
  Block getThenBlock();

  /**
   * Sets the value of the '{@link mil.navy.nrl.ncarai.jasm.program.IfThenElseStatement#getThenBlock <em>Then Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then Block</em>' containment reference.
   * @see #getThenBlock()
   * @generated
   */
  void setThenBlock(Block value);

  /**
   * Returns the value of the '<em><b>Else Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else Block</em>' containment reference.
   * @see #setElseBlock(Block)
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getIfThenElseStatement_ElseBlock()
   * @model containment="true"
   * @generated
   */
  Block getElseBlock();

  /**
   * Sets the value of the '{@link mil.navy.nrl.ncarai.jasm.program.IfThenElseStatement#getElseBlock <em>Else Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else Block</em>' containment reference.
   * @see #getElseBlock()
   * @generated
   */
  void setElseBlock(Block value);

} // IfThenElseStatement
