/**
 * generated by Xtext 2.20.0
 */
package mil.navy.nrl.ncarai.jasm.program;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Output Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.OutputStatement#getString <em>String</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.OutputStatement#getBindings <em>Bindings</em>}</li>
 * </ul>
 *
 * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getOutputStatement()
 * @model
 * @generated
 */
public interface OutputStatement extends Instruction
{
  /**
   * Returns the value of the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' attribute.
   * @see #setString(String)
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getOutputStatement_String()
   * @model
   * @generated
   */
  String getString();

  /**
   * Sets the value of the '{@link mil.navy.nrl.ncarai.jasm.program.OutputStatement#getString <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String</em>' attribute.
   * @see #getString()
   * @generated
   */
  void setString(String value);

  /**
   * Returns the value of the '<em><b>Bindings</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bindings</em>' containment reference.
   * @see #setBindings(Bindings)
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getOutputStatement_Bindings()
   * @model containment="true"
   * @generated
   */
  Bindings getBindings();

  /**
   * Sets the value of the '{@link mil.navy.nrl.ncarai.jasm.program.OutputStatement#getBindings <em>Bindings</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bindings</em>' containment reference.
   * @see #getBindings()
   * @generated
   */
  void setBindings(Bindings value);

} // OutputStatement
