/**
 * generated by Xtext 2.20.0
 */
package mil.navy.nrl.ncarai.jasm.program;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.jactr.io2.jactr.modelFragment.ChunkType;
import org.jactr.io2.jactr.modelFragment.Chunks;
import org.jactr.io2.jactr.modelFragment.Import;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Package Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.PackageDef#getName <em>Name</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.PackageDef#getTarget <em>Target</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.PackageDef#getImports <em>Imports</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.PackageDef#getIncludes <em>Includes</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.PackageDef#getGenerator <em>Generator</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.PackageDef#getBufferDefs <em>Buffer Defs</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.PackageDef#getChunkTypes <em>Chunk Types</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.PackageDef#getChunkDefs <em>Chunk Defs</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.PackageDef#getPatterns <em>Patterns</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.PackageDef#getFunctions <em>Functions</em>}</li>
 * </ul>
 *
 * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getPackageDef()
 * @model
 * @generated
 */
public interface PackageDef extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getPackageDef_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link mil.navy.nrl.ncarai.jasm.program.PackageDef#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' attribute.
   * @see #setTarget(String)
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getPackageDef_Target()
   * @model
   * @generated
   */
  String getTarget();

  /**
   * Sets the value of the '{@link mil.navy.nrl.ncarai.jasm.program.PackageDef#getTarget <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' attribute.
   * @see #getTarget()
   * @generated
   */
  void setTarget(String value);

  /**
   * Returns the value of the '<em><b>Imports</b></em>' containment reference list.
   * The list contents are of type {@link org.jactr.io2.jactr.modelFragment.Import}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imports</em>' containment reference list.
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getPackageDef_Imports()
   * @model containment="true"
   * @generated
   */
  EList<Import> getImports();

  /**
   * Returns the value of the '<em><b>Includes</b></em>' containment reference list.
   * The list contents are of type {@link mil.navy.nrl.ncarai.jasm.program.Include}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Includes</em>' containment reference list.
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getPackageDef_Includes()
   * @model containment="true"
   * @generated
   */
  EList<Include> getIncludes();

  /**
   * Returns the value of the '<em><b>Generator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Generator</em>' containment reference.
   * @see #setGenerator(GeneratorDef)
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getPackageDef_Generator()
   * @model containment="true"
   * @generated
   */
  GeneratorDef getGenerator();

  /**
   * Sets the value of the '{@link mil.navy.nrl.ncarai.jasm.program.PackageDef#getGenerator <em>Generator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Generator</em>' containment reference.
   * @see #getGenerator()
   * @generated
   */
  void setGenerator(GeneratorDef value);

  /**
   * Returns the value of the '<em><b>Buffer Defs</b></em>' containment reference list.
   * The list contents are of type {@link mil.navy.nrl.ncarai.jasm.program.BufferDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Buffer Defs</em>' containment reference list.
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getPackageDef_BufferDefs()
   * @model containment="true"
   * @generated
   */
  EList<BufferDef> getBufferDefs();

  /**
   * Returns the value of the '<em><b>Chunk Types</b></em>' containment reference list.
   * The list contents are of type {@link org.jactr.io2.jactr.modelFragment.ChunkType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chunk Types</em>' containment reference list.
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getPackageDef_ChunkTypes()
   * @model containment="true"
   * @generated
   */
  EList<ChunkType> getChunkTypes();

  /**
   * Returns the value of the '<em><b>Chunk Defs</b></em>' containment reference list.
   * The list contents are of type {@link org.jactr.io2.jactr.modelFragment.Chunks}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chunk Defs</em>' containment reference list.
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getPackageDef_ChunkDefs()
   * @model containment="true"
   * @generated
   */
  EList<Chunks> getChunkDefs();

  /**
   * Returns the value of the '<em><b>Patterns</b></em>' containment reference list.
   * The list contents are of type {@link mil.navy.nrl.ncarai.jasm.program.Pattern}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Patterns</em>' containment reference list.
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getPackageDef_Patterns()
   * @model containment="true"
   * @generated
   */
  EList<Pattern> getPatterns();

  /**
   * Returns the value of the '<em><b>Functions</b></em>' containment reference list.
   * The list contents are of type {@link mil.navy.nrl.ncarai.jasm.program.Function}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Functions</em>' containment reference list.
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getPackageDef_Functions()
   * @model containment="true"
   * @generated
   */
  EList<Function> getFunctions();

} // PackageDef
