/**
 * generated by Xtext 2.20.0
 */
package mil.navy.nrl.ncarai.jasm.program;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Retain As Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.RetainAsStatement#getRetained <em>Retained</em>}</li>
 * </ul>
 *
 * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getRetainAsStatement()
 * @model
 * @generated
 */
public interface RetainAsStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Retained</b></em>' containment reference list.
   * The list contents are of type {@link mil.navy.nrl.ncarai.jasm.program.AsStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Retained</em>' containment reference list.
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getRetainAsStatement_Retained()
   * @model containment="true"
   * @generated
   */
  EList<AsStatement> getRetained();

} // RetainAsStatement
