/**
 * generated by Xtext 2.20.0
 */
package mil.navy.nrl.ncarai.jasm.program;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Return Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.ReturnStatement#getReference <em>Reference</em>}</li>
 * </ul>
 *
 * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getReturnStatement()
 * @model
 * @generated
 */
public interface ReturnStatement extends Instruction
{
  /**
   * Returns the value of the '<em><b>Reference</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reference</em>' containment reference.
   * @see #setReference(ReturnVariableReference)
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getReturnStatement_Reference()
   * @model containment="true"
   * @generated
   */
  ReturnVariableReference getReference();

  /**
   * Sets the value of the '{@link mil.navy.nrl.ncarai.jasm.program.ReturnStatement#getReference <em>Reference</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reference</em>' containment reference.
   * @see #getReference()
   * @generated
   */
  void setReference(ReturnVariableReference value);

} // ReturnStatement
