/**
 * generated by Xtext 2.20.0
 */
package mil.navy.nrl.ncarai.jasm.program;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reward Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.RewardStatement#getReward <em>Reward</em>}</li>
 * </ul>
 *
 * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getRewardStatement()
 * @model
 * @generated
 */
public interface RewardStatement extends Instruction
{
  /**
   * Returns the value of the '<em><b>Reward</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reward</em>' attribute.
   * @see #setReward(Double)
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getRewardStatement_Reward()
   * @model
   * @generated
   */
  Double getReward();

  /**
   * Sets the value of the '{@link mil.navy.nrl.ncarai.jasm.program.RewardStatement#getReward <em>Reward</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reward</em>' attribute.
   * @see #getReward()
   * @generated
   */
  void setReward(Double value);

} // RewardStatement
