/**
 * generated by Xtext 2.20.0
 */
package mil.navy.nrl.ncarai.jasm.program;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Until Repeat Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.UntilRepeatStatement#getUntil <em>Until</em>}</li>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.UntilRepeatStatement#getBlock <em>Block</em>}</li>
 * </ul>
 *
 * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getUntilRepeatStatement()
 * @model
 * @generated
 */
public interface UntilRepeatStatement extends Instruction
{
  /**
   * Returns the value of the '<em><b>Until</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Until</em>' containment reference.
   * @see #setUntil(Until)
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getUntilRepeatStatement_Until()
   * @model containment="true"
   * @generated
   */
  Until getUntil();

  /**
   * Sets the value of the '{@link mil.navy.nrl.ncarai.jasm.program.UntilRepeatStatement#getUntil <em>Until</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Until</em>' containment reference.
   * @see #getUntil()
   * @generated
   */
  void setUntil(Until value);

  /**
   * Returns the value of the '<em><b>Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Block</em>' containment reference.
   * @see #setBlock(Block)
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getUntilRepeatStatement_Block()
   * @model containment="true"
   * @generated
   */
  Block getBlock();

  /**
   * Sets the value of the '{@link mil.navy.nrl.ncarai.jasm.program.UntilRepeatStatement#getBlock <em>Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Block</em>' containment reference.
   * @see #getBlock()
   * @generated
   */
  void setBlock(Block value);

} // UntilRepeatStatement
