/**
 * generated by Xtext 2.20.0
 */
package mil.navy.nrl.ncarai.jasm.program;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.VariableStatement#getAssignment <em>Assignment</em>}</li>
 * </ul>
 *
 * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getVariableStatement()
 * @model
 * @generated
 */
public interface VariableStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Assignment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assignment</em>' containment reference.
   * @see #setAssignment(AssignmentStatement)
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getVariableStatement_Assignment()
   * @model containment="true"
   * @generated
   */
  AssignmentStatement getAssignment();

  /**
   * Sets the value of the '{@link mil.navy.nrl.ncarai.jasm.program.VariableStatement#getAssignment <em>Assignment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assignment</em>' containment reference.
   * @see #getAssignment()
   * @generated
   */
  void setAssignment(AssignmentStatement value);

} // VariableStatement
