/**
 * generated by Xtext 2.20.0
 */
package mil.navy.nrl.ncarai.jasm.program;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>While</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mil.navy.nrl.ncarai.jasm.program.While#getBindings <em>Bindings</em>}</li>
 * </ul>
 *
 * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getWhile()
 * @model
 * @generated
 */
public interface While extends EObject
{
  /**
   * Returns the value of the '<em><b>Bindings</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bindings</em>' containment reference.
   * @see #setBindings(Bindings)
   * @see mil.navy.nrl.ncarai.jasm.program.ProgramPackage#getWhile_Bindings()
   * @model containment="true"
   * @generated
   */
  Bindings getBindings();

  /**
   * Sets the value of the '{@link mil.navy.nrl.ncarai.jasm.program.While#getBindings <em>Bindings</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bindings</em>' containment reference.
   * @see #getBindings()
   * @generated
   */
  void setBindings(Bindings value);

} // While
