/*
 * generated by Xtext 2.20.0
 */
package mil.navy.nrl.ncarai.jasm;

import com.google.inject.Guice;
import com.google.inject.Injector;
import mil.navy.nrl.ncarai.jasm.program.ProgramPackage;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.ISetup;
import org.eclipse.xtext.resource.IResourceFactory;
import org.eclipse.xtext.resource.IResourceServiceProvider;
import org.jactr.io2.jactr.ModelFragmentStandaloneSetup;

@SuppressWarnings("all")
public class ProgramStandaloneSetupGenerated implements ISetup {

	@Override
	public Injector createInjectorAndDoEMFRegistration() {
		ModelFragmentStandaloneSetup.doSetup();

		Injector injector = createInjector();
		register(injector);
		return injector;
	}
	
	public Injector createInjector() {
		return Guice.createInjector(new ProgramRuntimeModule());
	}
	
	public void register(Injector injector) {
		if (!EPackage.Registry.INSTANCE.containsKey("http://www.navy.mil/nrl/ncarai/jasm/Program")) {
			EPackage.Registry.INSTANCE.put("http://www.navy.mil/nrl/ncarai/jasm/Program", ProgramPackage.eINSTANCE);
		}
		IResourceFactory resourceFactory = injector.getInstance(IResourceFactory.class);
		IResourceServiceProvider serviceProvider = injector.getInstance(IResourceServiceProvider.class);
		
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("jasm", resourceFactory);
		IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("jasm", serviceProvider);
	}
}
