/**
 * generated by Xtext 2.19.0
 */
package mil.navy.nrl.ncarai.jasm.ui.wizard;

import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.ui.wizard.template.AbstractFileTemplate;
import org.eclipse.xtext.ui.wizard.template.FileTemplate;
import org.eclipse.xtext.ui.wizard.template.IFileGenerator;
import org.eclipse.xtext.ui.wizard.template.StringTemplateVariable;

@FileTemplate(label = "JASM Program", icon = "file_template.png", description = "Create an empty JASM program")
@SuppressWarnings("all")
public final class HelloWorldFile extends AbstractFileTemplate {
  private final StringTemplateVariable srcNamespace = this.text("Source Namespace", "", "Source namespace");
  
  private final StringTemplateVariable targetNamespace = this.text("Target Namespace", "", "Target namespace");
  
  @Override
  public void generateFiles(final IFileGenerator generator) {
    final String destination = this.srcNamespace.getValue().replace(".", "/");
    StringConcatenation _builder = new StringConcatenation();
    String _folder = this.getFolder();
    _builder.append(_folder);
    _builder.append("/");
    String _name = this.getName();
    _builder.append(_name);
    _builder.append(".jasm");
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("namespace ");
    _builder_1.append(this.srcNamespace);
    _builder_1.append(" target ");
    _builder_1.append(this.targetNamespace);
    _builder_1.append("{");
    _builder_1.newLineIfNotEmpty();
    _builder_1.append("import jactr.declarative.*");
    _builder_1.newLine();
    _builder_1.append("import jactr.procedural.*");
    _builder_1.newLine();
    _builder_1.append("import jactr.retrieval.*");
    _builder_1.newLine();
    _builder_1.append("import jactr.imaginal.*");
    _builder_1.newLine();
    _builder_1.append("import jactr.visual.*");
    _builder_1.newLine();
    _builder_1.append("import jactr.motor.*");
    _builder_1.newLine();
    _builder_1.append("import jactr.aural.*");
    _builder_1.newLine();
    _builder_1.append("import jactr.vocal.*");
    _builder_1.newLine();
    _builder_1.append("import jactr.goal.*");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    generator.generate(_builder, _builder_1);
  }
}
