/**
 * generated by Xtext 2.19.0
 */
package mil.navy.nrl.ncarai.jasm.ui;

import mil.navy.nrl.ncarai.jasm.ui.AbstractProgramUiModule;
import mil.navy.nrl.ncarai.jasm.ui.highlighting.HighlightingConfiguration;
import mil.navy.nrl.ncarai.jasm.ui.highlighting.SemanticHighlightingCalculator;
import mil.navy.nrl.ncarai.jasm.ui.hover.HoverProvider;
import mil.navy.nrl.ncarai.jasm.ui.hyperlink.JASMHyperlinkHelper;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;
import org.eclipse.xtext.ui.editor.hover.html.IEObjectHoverDocumentationProvider;
import org.eclipse.xtext.ui.editor.hyperlinking.IHyperlinkHelper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.jactr.io2.jactr.ui.validation.EclipseProjectAwareClassNameValidator;
import org.jactr.io2.jactr.validation.IClassNameValidator;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ProgramUiModule extends AbstractProgramUiModule {
  public Class<? extends IClassNameValidator> bindIClassNameValidator() {
    return EclipseProjectAwareClassNameValidator.class;
  }
  
  public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
    return HighlightingConfiguration.class;
  }
  
  public Class<? extends ISemanticHighlightingCalculator> bindIdeSemanticHighlightingCalculator() {
    return SemanticHighlightingCalculator.class;
  }
  
  public Class<? extends IHyperlinkHelper> bindIHyperlinkHelper() {
    return JASMHyperlinkHelper.class;
  }
  
  public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvder() {
    return HoverProvider.class;
  }
  
  public Class<? extends IEObjectHoverDocumentationProvider> bindIEObjectHoverDocumentationProvider() {
    return HoverProvider.class;
  }
  
  public ProgramUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
